version: "3.8"

services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb_optima
    restart: always
    environment:
      MYSQL_DATABASE: optima_db
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: optima_user
      MYSQL_PASSWORD: optima_pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - optima-network

  api:
    image: maven:3.9.9-eclipse-temurin-21
    container_name: api_optima_dev
    working_dir: /app
    restart: on-failure
    depends_on:
      - mysqldb
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    command: mvn spring-boot:run
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/optima_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: optima_user
      SPRING_DATASOURCE_PASSWORD: optima_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DEVTOOLS_RESTART_ENABLED: "true"
      SPRING_DEVTOOLS_LIVERELOAD_ENABLED: "true"
      JAVA_TOOL_OPTIONS: "-Dspring.devtools.restart.enabled=true -Dspring.devtools.restart.pollInterval=1000 -Dspring.devtools.restart.quietPeriod=400"
      SPRING_DEVTOOLS_RESTART_TRIGGER_FILE: ".reloadtrigger"
    networks:
      - optima-network

networks:
  optima-network:
    driver: bridge

volumes:
  db_data: